#!/bin/bash
ME=$(basename $0)

function usage() {
    echo "Usage: ${ME} [branch name]"
    exit 1
}

branchname=${1}

if [ -z "${1}" ]; then
    usage
else
    branchname=${1}
fi

echo "git checkout -b ${branchname}"
git checkout -b ${branchname} || exit 1

echo "git push origin ${branchname}"
git push origin ${branchname} || exit 1

git branch -l

echo "done"
