#!/bin/bash
ME=$(basename $0)

function usage() {
    echo "Usage: ${ME} [tag name]"
    echo "       ${ME} [tag name] [commit]"
    exit 1
}

tagname=${1}

if [ -z "${1}" ]; then
    usage
else
    tagname=${1}
fi

if [ ! -z "${2}" ]; then
    commit=${2}
fi

if [ -z "${commit}" ]; then
    echo "git tag ${tagname}"
    git tag ${tagname}
else
    echo "git tag ${tagname} ${commit}"
    git tag ${tagname} ${commit}
fi

echo "git push origin ${tagname}"
git push origin ${tagname}

echo "done"
