#!/bin/bash
# refer to https://stackoverflow.com/questions/43015808/how-to-automatically-find-the-upstream-url-for-a-fork-on-github-without-hub

url=$(git config --get remote.origin.url)
#repo=${url##*/}
repo=$(basename -s .git $url)
user=$(echo "$url" | awk -F/ '{print $4}')

# method1 - with jq
function add_upstream_method1() {
    remote=$(curl -s "https://api.github.com/repos/$user/$repo" | jq -r '.parent.clone_url')
    if [ "$remote" != "null" ]; then
        git remote add upstream "$remote"
    else
        echo "no upstream found"
    fi
}

# method2 - withoud jq
function add_upstream_method2() {
    remote=$(curl -s "https://api.github.com/repos/$user/$repo" | awk 'match($0, /\"clone_url\"\s*:\s*\"(.*)\"/, a) {last=a[1]}END{print last}')
    if [ ! -z "$remote" ]; then
        git remote add upstream "$remote"
    else
        echo "no upstream found"
    fi
}

if ! [ -x "$(command -v jq)" ]; then
    #echo 'jq is not installed.' >&2
    add_upstream_method2
else
    add_upstream_method1
fi

git remote -v
