#!/bin/bash
# Show current branch or switch to a branch
# refer to https://stackoverflow.com/questions/6245570/how-to-get-the-current-branch-name-in-git

ME=$(basename $0)

function usage() {
    echo "Usage: ${ME} - show current branch"
    echo "Usage: ${ME} [branch name] - switch to branch"
    exit 1
}

branchname=${1}

if [ -z "${branchname}" ]; then
    # method-1
    git rev-parse --abbrev-ref HEAD

    # method-2
    #git branch | grep \* | cut -d ' ' -f2

    # method-3
    # git symbolic-ref --short HEAD
else
    git checkout ${branchname}
    git branch -l
fi
