#!/bin/bash
# Show current branch
# refer to https://stackoverflow.com/questions/6245570/how-to-get-the-current-branch-name-in-git

# method-1
git rev-parse --abbrev-ref HEAD

# method-2
#git branch | grep \* | cut -d ' ' -f2
