#!/bin/bash
ME=$(basename $0)

function usage() {
    echo "Usage: ${ME} [branch name]"
    exit 1
}

branchname=${1}

if [ -z "${1}" ]; then
    usage
else
    branchname=${1}
fi

echo "git checkout master"
git checkout master || exit 1

echo "git branch -d ${branchname}"
git branch -d ${branchname} || exit 1

echo "git push origin --delete ${branchname}"
git push origin --delete ${branchname} || exit 1

git branch -l

echo "done"
