#!/bin/bash
ME=$(basename $0)

function usage() {
    echo "Usage: ${ME} [file1] [file2] ..."
    exit 1
}

if [ -z "${1}" ]; then
    usage
fi

for fn in $@; do
    if [[ -d ${fn} ]]; then
        echo "rm -rf --preserve-root ${fn}"
        rm -rf --preserve-root ${fn} || exit 1
    elif [[ -f ${fn} ]]; then
        echo "rm -f --preserve-root ${fn}"
        rm -f --preserve-root ${fn} || exit 1
    fi
    echo "git checkout ${fn}"
    git checkout ${fn} || exit 1
done

echo "done"
