#!/bin/bash
ME=$(basename $0)

function usage() {
    echo "Usage: ${ME} [commit]"
    exit 1
}

commit=${1}

if [ -z "${1}" ]; then
    usage
else
    commit=${1}
fi

git diff ${commit}^ ${commit} || exit 1
