#!/bin/bash
ME=$(basename $0)

function usage() {
    echo "Usage: ${ME} [commit]"
    exit 1
}

commit=${1}

if [ -z "${1}" ]; then
    usage
else
    commit=${1}
fi

git --no-pager diff ${commit}^ ${commit} --name-status || exit 1
