#!/bin/bash
TOPDIR=$(pwd)

if [ -f .git/config ]; then
    git --no-pager log -1 HEAD
    echo
fi

for D in *
do
    if [ -d "${TOPDIR}/${D}" ]; then
        if [ -f ${TOPDIR}/${D}/.git/config ]; then
            echo ${D}
            cd ${TOPDIR}/${D};git --no-pager log -1 HEAD
            echo
        fi
    fi
done
