#!/bin/bash
TOPDIR=$(pwd)

COLOR_REST='\e[0m'
COLOR_GREEN='\e[0;32m';
COLOR_RED='\e[0;31m';
COLOR_YELLOW='\e[1;33m';
COLOR_CYAN='\e[0;36m';

function print_green()
{
    echo -e "${COLOR_GREEN}$1${COLOR_REST}"
}

function print_yellow()
{
    echo -e "${COLOR_YELLOW}$1${COLOR_REST}"
}

function print_red()
{
    echo -e "${COLOR_RED}$1${COLOR_REST}"
}

function print_cyan()
{
    echo -e "${COLOR_CYAN}$1${COLOR_REST}"
}

function failed()
{
    echo "$*" >&2
    exit 1
}

if [ -f .git/config ]; then
    git pull
fi

for D in *
do
    if [ -d "${TOPDIR}/${D}" ]; then
        if [ -f ${TOPDIR}/${D}/.git/config ]; then
            #echo ${D}
            print_green "${D}"
            cd ${TOPDIR}/${D};git pull;git fetch --tags --all -f
            echo
        fi
    fi
done
