#!/bin/bash
# refer to https://magiclen.org/git-remove-commited-files/
# refer to https://gitbook.tw/chapters/faq/remove-files-from-git.html
# real remove files from git repository
ME=$(basename $0)

function usage() {
    echo "Usage: ${ME} [file]"
    exit 1
}

file=${@}

if [ -z "${file}" ]; then
    usage
fi

#method1
  git filter-branch --force --tree-filter "rm -rf ${file}" -- --all
  git filter-branch --force
  git reflog expire --all --expire=now
  git gc --prune=now

#method2
  #git filter-branch -f --prune-empty --tag-name-filter cat --tree-filter 'rm -rf ${file}' -- --all
  #git for-each-ref --format="%(refname)" refs/original/ | xargs -n 1 git update-ref -d
