#!/bin/bash
# refer to https://magiclen.org/git-remove-commited-files/
# refer to https://gitbook.tw/chapters/faq/remove-files-from-git.html
# real remove files from git repository
ME=$(basename $0)

function usage() {
    echo "Usage: ${ME} [file1] [file2] [folder1] [folder2] ..."
    exit 1
}

file=${1}

if [ -z "${file}" ]; then
    usage
fi

for f in $@; do
    git filter-branch --force --tree-filter "rm -rf ${f}" -- --all

done

git filter-branch --force
git reflog expire --all --expire=now
git gc --prune=now
