#!/bin/bash
# refer to https://magiclen.org/git-remove-commited-files/
# refer to https://gitbook.tw/chapters/faq/remove-files-from-git.html
# real remove files from git repository
ME=$(basename $0)

USAGE_STR="$(cat <<EOF
Usage: ${ME} [file]
Ex:
  If file need to be deleted like this with multiple space characters
     Prerequisites/Visual C++ Redistributable for Visual Studio 2013/vcredist_2013u5_x86.exe
  Run:
     ${ME} "Prerequisites/Visual C++ Redistributable for Visual Studio 2013/vcredist_2013u5_x86.exe"
EOF
)"

function usage() {
    echo "$USAGE_STR"
    exit 0
}

file=${@}

if [ -z "${file}" ]; then
    usage
fi

#method-1
  #git filter-branch --force --tree-filter "rm -rf ${file}" -- --all
  #git filter-branch --force
  #git reflog expire --all --expire=now
  #git gc --prune=now

#method-2
#this method work if path have space
#ex: if file need to be deleted ,
# Prerequisites/Visual C++ Redistributable for Visual Studio 2013/vcredist_2013u5_x86.exe
#
  cmd="rm -rf \"${file}\""
  git filter-branch -f --prune-empty --tag-name-filter cat --tree-filter "${cmd}" -- --all
  git for-each-ref --format="%(refname)" refs/original/ | xargs -n 1 git update-ref -d
  git reflog expire --all --expire=now
  git gc --prune=now
