#!/bin/bash
# Delete the last commit both local and remote
FORCE_MODE=n

while getopts "f" opt; do
    case $opt in
    f)
       FORCE_MODE=y
       ;;
    esac
done

ins=n
if [ "${FORCE_MODE}" == "y" ]; then
    echo "Are you sure you want to continue? [y/n] y"
    ins=y
else
    read -p "Are you sure you want to continue? [y/n]" ins
fi

if [ "${ins}" != "y" ] && [ "${ins}" != "Y" ]; then
    exit 0
fi

git reset --hard HEAD^
git push origin HEAD --force
