#!/bin/bash
TOPDIR=$(pwd)

if [ -f .git/config ]; then
    git status --short
fi

for D in *
do
    if [ -d "${TOPDIR}/${D}" ]; then
        if [ -f ${TOPDIR}/${D}/.git/config ]; then
            echo ${D}
            cd ${TOPDIR}/${D};git status --short
        fi
    fi
done
