#!/bin/bash
git checkout master || exit 1
git pull upstream master || exit 1

ins=n
echo "local master sync ... done"
read -p "git push origin master ? [y/n]" ins

if [ "${ins}" != "y" ] && [ "${ins}" != "Y" ]; then
    exit 0
fi

git push origin master || exit 1

echo "done"
