#!/bin/bash
currbranch=$(git rev-parse --abbrev-ref HEAD)
read -p "git pull upstream master to current branch - $currbranch ? [y/n]" ins
if [ "${ins}" != "y" ] && [ "${ins}" != "Y" ]; then
    exit 0
fi

git pull upstream master || exit 1

ins=n
read -p "git push origin $currbranch ? [y/n]" ins

if [ "${ins}" != "y" ] && [ "${ins}" != "Y" ]; then
    exit 0
fi

git push origin $currbranch || exit 1

echo "done"
